### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by JoeLittell** [cbail/ids704#2]
@cbail @katevcoulter 

I am currently working through the 'Application Programming Interfaces in R' section and under the  'How does an API work?'  subsection there is a practical exercise for using Google Maps looking at Duke. The issue is Google Maps now requires authentication and kicks back this error:

{
   "error_message" : "You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account",
   "results" : [],
   "status" : "REQUEST_DENIED"
}

Do we want to expose an API key to show it properly, or add a new section, similar to the one below it for Facebook, or simply rely off of the screenshot and remove the links?

**Comment by cbail** [comment]
Hey Joe- check out what we did in SICSS last year, I know this came up last year. If you can't find the 2019 materials let me know but they should be linked here: https://github.com/compsocialscience/summer-institute/tree/master/2019/materials
